main: one.sweptthr.ljsplugin.Main
name: LJSPlugin
version: 2
api-version: 1.14
author: SweptThrone
description: Move back and forth from a survival world with ease.
commands:
    ljs:
        description: Root command for LJS
        usage: /ljs